### ISSUE TITLE
Can't build process_jam_log on develop

### ISSUE THREAD

**Issue by teeks99** [boostorg/regression#57]
It is [depending](https://github.com/boostorg/regression/blob/80d44c58655779fbfa0dee9b473ed2b2faffe625/common/src/process_jam_log.cpp#L20C43-L20C44) on the `filesystem/convenience.hpp`, which was just removed in [this commit](https://github.com/boostorg/filesystem/commit/5df060e95ca844fe91b29001b4ae22bdb65635c6#diff-240a54fddee6ad9fe49348bd85eb1707092d0da24481cfb8f37ebf466b93f58e).

**Comment by pdimov** [comment]
This https://github.com/boostorg/regression/commit/bf15f418a4434b553de19355f7f6ae27fa79bd9d fixes it for me.

**Comment by teeks99** [comment]
That solved it, thank you.
